/**
 * Neuraloop Phase 20 — AI Workflow Architect Knowledge Base
 * Central registry describing all 20 registered nodes, 18 official templates,
 * and 5 core workflow architecture patterns for AI workflow planning and generation.
 */

export interface NodeSpec {
  id: string;
  name: string;
  category: "trigger" | "action" | "logic";
  description: string;
  isTrigger: boolean;
  requiredCredentials?: string[];
  supportedAuthTypes?: string[];
  inputs: string[];
  outputs: string[];
  commonUseCases: string[];
  bestPractices: string[];
}

export interface ArchitecturePattern {
  id: "Notification" | "Approval" | "Research" | "Monitoring" | "Content Generation" | "Custom";
  name: string;
  description: string;
  recommendedNodes: string[];
  examplePrompt: string;
}

export interface TemplateSpec {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  requiredNodes: string[];
  pattern: ArchitecturePattern["id"];
}

// 1. All 20 Registered Nodes Specification Matrix
export const NODE_KNOWLEDGE_SPECS: Record<string, NodeSpec> = {
  "manual-trigger": {
    id: "manual-trigger",
    name: "Manual Trigger",
    category: "trigger",
    description: "Triggers a workflow run manually via dashboard button or API call.",
    isTrigger: true,
    inputs: [],
    outputs: ["timestamp", "user"],
    commonUseCases: ["Testing workflows", "Ad-hoc task execution", "On-demand batch runs"],
    bestPractices: ["Use for testing initial graph logic before attaching automated triggers."],
  },
  webhook: {
    id: "webhook",
    name: "Webhook Trigger",
    category: "trigger",
    description: "Listens for incoming HTTP POST/GET requests to trigger execution.",
    isTrigger: true,
    inputs: [],
    outputs: ["headers", "query", "body", "method"],
    commonUseCases: ["Form submissions", "GitHub webhooks", "Stripe payment events", "Custom app webhooks"],
    bestPractices: ["Validate incoming payload structure with a Transform or IF node immediately after."],
  },
  schedule: {
    id: "schedule",
    name: "Schedule Trigger",
    category: "trigger",
    description: "Triggers workflows on recurring cron intervals or preset schedules.",
    isTrigger: true,
    inputs: [],
    outputs: ["timestamp", "cronExpression"],
    commonUseCases: ["Daily morning digests", "Hourly server monitoring", "Weekly report generation"],
    bestPractices: ["Use cron syntax for precise minute/hour timing."],
  },
  "http-request": {
    id: "http-request",
    name: "HTTP Request Pro",
    category: "action",
    description: "Dispatches HTTP GET/POST/PUT/DELETE API calls with OAuth bridge or Vault credentials.",
    isTrigger: false,
    requiredCredentials: ["oauth_connection", "api_key", "bearer_token", "basic_auth"],
    supportedAuthTypes: ["oauth_connection", "vault", "bearer", "basic", "api_key", "custom_header"],
    inputs: ["url", "method", "headers", "queryParams", "body", "authType", "connectionProvider"],
    outputs: ["status", "headers", "body", "data"],
    commonUseCases: ["Fetching weather/news APIs", "GitHub API calls", "Slack chat.postMessage", "REST API integration"],
    bestPractices: ["Use authType: 'oauth_connection' for GitHub, Slack, and Google Workspace APIs."],
  },
  ai: {
    id: "ai",
    name: "AI Agent / LLM",
    category: "action",
    description: "Executes LLM prompts using OpenAI, Claude 3.5 Sonnet, or Gemini models.",
    isTrigger: false,
    requiredCredentials: ["openai_api_key", "claude_api_key", "gemini_api_key"],
    inputs: ["provider", "model", "prompt", "systemPrompt", "credentialId"],
    outputs: ["text", "model", "provider", "usage"],
    commonUseCases: ["Sentiment classification", "Text summarization", "Content drafting", "Code review"],
    bestPractices: ["Provide clear prompt context using handlebars expressions like {{input.message}}."],
  },
  slack: {
    id: "slack",
    name: "Slack",
    category: "action",
    description: "Posts text messages or notifications to Slack channels.",
    isTrigger: false,
    requiredCredentials: ["slack_oauth_token", "slack_webhook_url"],
    inputs: ["channel", "message", "text"],
    outputs: ["success", "ts", "channel"],
    commonUseCases: ["Team alerts", "Incident notifications", "Lead qualification alerts"],
    bestPractices: ["Reference channel names like #general or #leads."],
  },
  email: {
    id: "email",
    name: "Email Notification",
    category: "action",
    description: "Sends SMTP email notifications to one or more recipient addresses.",
    isTrigger: false,
    requiredCredentials: ["smtp_credentials"],
    inputs: ["to", "subject", "body"],
    outputs: ["sent", "messageId", "recipient"],
    commonUseCases: ["Executive summaries", "Welcome emails", "Daily digest delivery"],
    bestPractices: ["Format subjects clearly with emojis and recipient handles."],
  },
  telegram: {
    id: "telegram",
    name: "Telegram",
    category: "action",
    description: "Dispatches formatted text or Markdown alerts to Telegram channels or chats.",
    isTrigger: false,
    requiredCredentials: ["telegram_bot_token"],
    inputs: ["chatId", "message", "parseMode"],
    outputs: ["success", "messageId"],
    commonUseCases: ["Instant uptime alerts", "Daily tip broadcasts", "Hot lead notifications"],
    bestPractices: ["Use parseMode: 'Markdown' for bold/italic formatted alert texts."],
  },
  discord: {
    id: "discord",
    name: "Discord",
    category: "action",
    description: "Posts text content or rich color embeds to Discord webhooks.",
    isTrigger: false,
    requiredCredentials: ["discord_webhook_url"],
    inputs: ["messageType", "content", "embedTitle", "embedDescription", "embedColor"],
    outputs: ["success"],
    commonUseCases: ["Developer PR summaries", "Tech news digests", "Incident monitoring"],
    bestPractices: ["Use embed messageType for rich formatted headlines."],
  },
  "google-sheets": {
    id: "google-sheets",
    name: "Google Sheets",
    category: "action",
    description: "Reads spreadsheet row ranges or appends new rows to Google Sheets.",
    isTrigger: false,
    requiredCredentials: ["google_oauth_token"],
    inputs: ["operation", "spreadsheetId", "range", "valuesJson"],
    outputs: ["values", "updatedRange", "updatedRows"],
    commonUseCases: ["Lead logging", "Content calendar archiving", "Batch topic processing"],
    bestPractices: ["Pass valid JSON string array for valuesJson parameter."],
  },
  loop: {
    id: "loop",
    name: "Loop",
    category: "logic",
    description: "Sequentially iterates over array elements for downstream processing.",
    isTrigger: false,
    inputs: ["arrayInput", "arrayPath"],
    outputs: ["item", "index", "total"],
    commonUseCases: ["Batch processing sheet rows", "Iterating social post drafts"],
    bestPractices: ["Connect downstream steps to loop handle for per-item execution."],
  },
  switch: {
    id: "switch",
    name: "Switch",
    category: "logic",
    description: "Routes workflow execution across multiple conditional branch handles.",
    isTrigger: false,
    inputs: ["cases", "defaultHandle"],
    outputs: ["case_1", "case_2", "default"],
    commonUseCases: ["Multi-category ticket routing", "Lead score tiering", "Status code branching"],
    bestPractices: ["Always include a defaultHandle target for unmapped cases."],
  },
  merge: {
    id: "merge",
    name: "Merge",
    category: "logic",
    description: "Consolidates parallel execution paths into a single output payload.",
    isTrigger: false,
    inputs: ["mode"],
    outputs: ["combined"],
    commonUseCases: ["Combining multi-channel digest streams", "Joining parallel API outputs"],
    bestPractices: ["Place immediately after parallel action branches."],
  },
  transform: {
    id: "transform",
    name: "Transform Data",
    category: "logic",
    description: "Manipulates, reshapes, formats, flattens, or sets field default values.",
    isTrigger: false,
    inputs: ["operation", "defaults", "sourcePath", "stringAction"],
    outputs: ["result"],
    commonUseCases: ["Setting lead field defaults", "Flattening sheet row matrices", "Trimming text"],
    bestPractices: ["Use set_default_values to ensure downstream nodes don't receive null fields."],
  },
  "set-variable": {
    id: "set-variable",
    name: "Set Variable",
    category: "logic",
    description: "Defines static or dynamic key-value state variables.",
    isTrigger: false,
    inputs: ["variables"],
    outputs: ["variableMap"],
    commonUseCases: ["Tagging candidate statuses", "Defining environment constants"],
    bestPractices: ["Keep variable names clean and lowercase."],
  },
  delay: {
    id: "delay",
    name: "Delay Execution",
    category: "logic",
    description: "Pauses workflow execution for a specified duration.",
    isTrigger: false,
    inputs: ["duration", "unit"],
    outputs: ["completedAt"],
    commonUseCases: ["Onboarding email sequences", "Rate limit backoff intervals"],
    bestPractices: ["Specify unit as 'seconds', 'minutes', or 'hours'."],
  },
  code: {
    id: "code",
    name: "Custom Code",
    category: "action",
    description: "Executes custom JavaScript code snippet to transform data.",
    isTrigger: false,
    inputs: ["jsCode"],
    outputs: ["result"],
    commonUseCases: ["Complex mathematical calculations", "Custom regex string manipulation"],
    bestPractices: ["Return an object from the code snippet."],
  },
  "webhook-response": {
    id: "webhook-response",
    name: "Webhook Response",
    category: "action",
    description: "Returns custom HTTP response payload and status code to webhooks.",
    isTrigger: false,
    inputs: ["statusCode", "body"],
    outputs: ["responded"],
    commonUseCases: ["Synchronous webhook responses", "API gateway endpoints"],
    bestPractices: ["Use 200 OK status code for successful webhook processing."],
  },
  if: {
    id: "if",
    name: "IF Condition",
    category: "logic",
    description: "Evaluates condition expression to select TRUE or FALSE handle branch.",
    isTrigger: false,
    inputs: ["fieldPath", "operator", "value"],
    outputs: ["true", "false"],
    commonUseCases: ["Lead score evaluation", "High priority thresholds"],
    bestPractices: ["Connect both true and false handles to complete workflow branches."],
  },
  filter: {
    id: "filter",
    name: "Filter Data",
    category: "logic",
    description: "Filters payload data against matching rule before continuing execution.",
    isTrigger: false,
    inputs: ["fieldPath", "operator", "targetValue"],
    outputs: ["passed"],
    commonUseCases: ["Excluding spam submissions", "Filtering active accounts"],
    bestPractices: ["Place directly after trigger or data read nodes."],
  },
};

// 2. Core Architecture Patterns
export const ARCHITECTURE_PATTERNS: ArchitecturePattern[] = [
  {
    id: "Notification",
    name: "Notification & Alert Pattern",
    description: "Captures an event or runs on schedule, processes text via AI, and dispatches alerts to messaging channels.",
    recommendedNodes: ["webhook", "schedule", "ai", "telegram", "discord", "slack", "email"],
    examplePrompt: "Send daily AI summaries to Telegram or Slack",
  },
  {
    id: "Approval",
    name: "Approval & Routing Pattern",
    description: "Ingests data, evaluates priority/urgency using AI, and routes payload down distinct handle branches with Switch/IF.",
    recommendedNodes: ["webhook", "ai", "switch", "if", "telegram", "google-sheets", "email"],
    examplePrompt: "Qualify incoming leads using AI and route hot leads to Telegram",
  },
  {
    id: "Research",
    name: "Research & Extraction Pattern",
    description: "Fetches target web feed or sheet rows, reshapes payload with Transform, synthesizes insights with AI, and writes results.",
    recommendedNodes: ["schedule", "google-sheets", "http-request", "transform", "ai", "google-sheets"],
    examplePrompt: "Read topics from Google Sheets, research insights with AI, and save results",
  },
  {
    id: "Monitoring",
    name: "Monitoring & Health Check Pattern",
    description: "Pings server or inspects web page via HTTP GET, checks status code with Switch/IF, and fires urgent alerts.",
    recommendedNodes: ["schedule", "http-request", "switch", "if", "discord", "telegram"],
    examplePrompt: "Monitor website uptime every 5 minutes and alert Discord if server fails",
  },
  {
    id: "Content Generation",
    name: "Content Generation & Calendar Pattern",
    description: "Generates creative post variations with AI, iterates items with Loop, and archives items to Google Sheets or social channels.",
    recommendedNodes: ["schedule", "ai", "loop", "google-sheets"],
    examplePrompt: "Draft weekly social posts with AI and log drafts to Google Sheets content calendar",
  },
];

// 3. Template Specifications Catalog for AI Intent Matching
export const OFFICIAL_TEMPLATE_SPECS: TemplateSpec[] = [
  {
    id: "tpl-1",
    name: "Daily AI Summary",
    description: "Scheduled morning trigger that asks AI for daily productivity tips and broadcasts them directly to a Telegram channel.",
    category: "AI",
    tags: ["telegram", "ai", "schedule", "productivity", "daily"],
    requiredNodes: ["schedule", "ai", "telegram"],
    pattern: "Notification",
  },
  {
    id: "tpl-2",
    name: "Discord AI News Bot",
    description: "Scheduled bot that queries AI for daily news digests and posts rich embeds to a Discord channel via Webhook.",
    category: "AI",
    tags: ["discord", "ai", "schedule", "bot", "news"],
    requiredNodes: ["schedule", "ai", "discord"],
    pattern: "Notification",
  },
  {
    id: "tpl-3",
    name: "Google Sheets AI Analyzer",
    description: "Read row data from Google Sheets, run sentiment or classification analysis with AI, and append results back to Google Sheets.",
    category: "Productivity",
    tags: ["google-sheets", "ai", "data", "analytics", "sheets"],
    requiredNodes: ["google-sheets", "ai", "google-sheets"],
    pattern: "Research",
  },
  {
    id: "tpl-4",
    name: "Contact Form Tracker",
    description: "Capture website form submissions via incoming webhooks, normalize lead fields, and append records into Google Sheets.",
    category: "Sales",
    tags: ["google-sheets", "webhook", "transform", "leads", "sales", "form"],
    requiredNodes: ["webhook", "transform", "google-sheets"],
    pattern: "Approval",
  },
  {
    id: "tpl-5",
    name: "Telegram Alert System",
    description: "Receive incoming webhooks or alerts and instantly route message notifications to a Telegram chat or channel.",
    category: "Communication",
    tags: ["telegram", "webhook", "alerts", "communication"],
    requiredNodes: ["webhook", "telegram"],
    pattern: "Notification",
  },
  {
    id: "tpl-6",
    name: "AI Email Digest Generator",
    description: "Fetches content feed via HTTP GET, formats payload with Transform, generates an executive summary using AI, and emails subscribers.",
    category: "AI",
    tags: ["ai", "email", "transform", "http-request", "schedule", "digest"],
    requiredNodes: ["schedule", "http-request", "transform", "ai", "email"],
    pattern: "Notification",
  },
  {
    id: "tpl-7",
    name: "AI Lead Qualification Bot",
    description: "Ingests incoming leads via webhook, normalizes defaults with Transform, evaluates intent and budget using AI, and routes qualified leads to Telegram or logs them in Google Sheets.",
    category: "Sales",
    tags: ["sales", "ai", "transform", "switch", "telegram", "google-sheets", "qualify", "leads"],
    requiredNodes: ["webhook", "transform", "ai", "switch", "telegram", "google-sheets"],
    pattern: "Approval",
  },
  {
    id: "tpl-8",
    name: "AI Support Ticket Router",
    description: "Analyzes customer support ticket text with AI, classifies urgency/category, and routes to appropriate branch queues.",
    category: "Customer Support",
    tags: ["support", "ai", "switch", "webhook", "ticket", "router"],
    requiredNodes: ["webhook", "ai", "switch"],
    pattern: "Approval",
  },
  {
    id: "tpl-9",
    name: "Competitor Monitoring Agent",
    description: "Periodically inspects competitor landing page content via HTTP GET, detects changes using AI, and alerts your team on Discord.",
    category: "Operations",
    tags: ["monitoring", "http-request", "ai", "discord", "competitor"],
    requiredNodes: ["schedule", "http-request", "ai", "discord"],
    pattern: "Monitoring",
  },
  {
    id: "tpl-10",
    name: "AI Social Media Content Factory",
    description: "Generates weekly social media content variations using AI, loops through output posts, and archives drafts into Google Sheets.",
    category: "Marketing",
    tags: ["marketing", "ai", "loop", "google-sheets", "social", "content"],
    requiredNodes: ["schedule", "ai", "loop", "google-sheets"],
    pattern: "Content Generation",
  },
  {
    id: "tpl-11",
    name: "Website Uptime Monitor",
    description: "Pings server endpoint every 5 minutes, checks HTTP response code with Switch condition logic, and fires urgent Telegram downtime alerts.",
    category: "Operations",
    tags: ["monitoring", "uptime", "http-request", "telegram", "ping"],
    requiredNodes: ["schedule", "http-request", "switch", "telegram"],
    pattern: "Monitoring",
  },
  {
    id: "tpl-12",
    name: "AI Meeting Notes Distributor",
    description: "Receives raw meeting transcripts via webhook, synthesizes action items using AI, merges summary streams, and distributes to Email & Discord.",
    category: "Productivity",
    tags: ["productivity", "ai", "merge", "email", "discord", "meeting", "notes"],
    requiredNodes: ["webhook", "ai", "merge", "email", "discord"],
    pattern: "Notification",
  },
  {
    id: "tpl-13",
    name: "AI Research Assistant",
    description: "Reads company research topics from Google Sheets, flattens & filters topics with Transform, iterates over rows with Loop, researches insights using AI, and writes results back.",
    category: "Productivity",
    tags: ["google-sheets", "transform", "loop", "ai", "research", "sheets"],
    requiredNodes: ["google-sheets", "transform", "loop", "ai", "google-sheets"],
    pattern: "Research",
  },
  {
    id: "tpl-14",
    name: "Smart Job Application Tracker",
    description: "Ingests incoming job applications via webhook, formats application data with Set Variable, logs to Google Sheets, and alerts hiring manager on Telegram.",
    category: "HR",
    tags: ["hr", "webhook", "set-variable", "google-sheets", "telegram", "job", "applicant"],
    requiredNodes: ["webhook", "set-variable", "google-sheets", "telegram"],
    pattern: "Approval",
  },
  {
    id: "tpl-15",
    name: "Content Approval Workflow",
    description: "Receives draft articles via webhook, runs AI quality checks, and routes content to Approval or Revision handles.",
    category: "Marketing",
    tags: ["marketing", "ai", "switch", "webhook", "approval", "content"],
    requiredNodes: ["webhook", "ai", "switch"],
    pattern: "Approval",
  },
  {
    id: "tpl-16",
    name: "GitHub PR Reviewer",
    description: "Captures GitHub pull_request webhook events, fetches diff payload via GitHub OAuth, analyzes code quality using AI, and posts review summary to Slack.",
    category: "Developer Tools",
    tags: ["github", "oauth", "ai", "slack", "pr", "code"],
    requiredNodes: ["webhook", "http-request", "ai", "slack"],
    pattern: "Approval",
  },
  {
    id: "tpl-17",
    name: "GitHub Issue Summarizer",
    description: "Ingests GitHub issue webhooks, summarizes customer bug reports using AI, and broadcasts findings to a Telegram channel.",
    category: "Developer Tools",
    tags: ["github", "oauth", "ai", "telegram", "issue"],
    requiredNodes: ["webhook", "ai", "telegram"],
    pattern: "Notification",
  },
  {
    id: "tpl-18",
    name: "Slack Incident Monitor",
    description: "Monitors incident alert webhooks, generates an executive incident triage brief with AI, and posts to Slack using Slack OAuth Connection.",
    category: "Operations",
    tags: ["slack", "oauth", "ai", "monitoring", "incident"],
    requiredNodes: ["webhook", "ai", "http-request"],
    pattern: "Monitoring",
  },
];
